[theme]
primaryColor = "#087E5B"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18212B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

